### ISSUE TITLE
Better description?

### ISSUE THREAD

**Issue by impressivewebs** [iamstarkov/generator-travis#5]
Hi, I'd like to include this in my Newsletter, but I don't really understand what this is. My questions:
- What is "travis"? Do mean this: https://travis-ci.org/
- What do you mean by "travis config"?
- It says you won't lose existing config. Existing config in what?
- To install, it says to use the "yo" command. Does that mean this is a Yeoman plugin? Is this a scaffolding tool/plugin or something?

I don't use Yeoman or Travis or similar tools, but I just want to see if maybe your description could be improved to help people understand why this tool might be useful. Thanks.

**Comment by iamstarkov** [comment]
Hi Louis,

It’s great that you wrote me. Let’s see how we can improve documentation to help people to understand why this tool can be useful.

> What is "travis"? Do mean this: https://travis-ci.org/ 

Yep, I mean exactly it. Travis CI or just travis.

> What do you mean by "travis config"?

I mean `.travis.yml` — it is the configuration file for Travis CI. Travis CI uses `.travis.yml` file in the root of repository to learn about project and how developer want their builds to be executed. There is also [documentation](http://docs.travis-ci.com/user/customizing-the-build/) for this config file.

> It says you won't lose existing config. Existing config in what?

I mean existing travis config, if project is not new, then generator-travis can be usefull to get up-to-date NodeJS versions. For example, I will use generator-travis once in a while to setup and test my projects in modern NodeJS versions, and I will not be afraid of loosing other options from travis config in those projects. This note is here because it’s common in yeoman community to overwrite existing files.

> To install, it says to use the "yo" command. Does that mean this is a Yeoman plugin? Is this a scaffolding tool/plugin or something?

Yep, it is a tiny yeoman scaffolding tool to setup proper Continuous Integration environment for your projects.

How do you think, what part of this answer can be included to the README to make it more clear?

**Comment by impressivewebs** [comment]
Ok, I think that explains it better. You should definitely mention that it's a Yeoman tool. If you can include all the details you just mentioned, that would be good. But anyhow, it's up to you. I just wanted to confirm so I can know what category it would go under in my newsletter and how I can describe it so it's easy to understand (I usually include one or two brief sentences that summarize exactly what each tool is, but the description needs to be easy to understand). Thanks!

**Comment by iamstarkov** [comment]
Just published `1.1.5` with updated docs, @impressivewebs pls take a look https://github.com/iamstarkov/generator-travis#readme

**Comment by iamstarkov** [comment]
this issue should be resolved now, if you think there is still a room for improvement, pls let me know
